import React, {
  createContext,
  useContext,
  useState,
  type ReactNode,
} from "react";

type Language = "ar" | "en";

interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  t: (key: string, page?: string) => string;
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined
);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

// ترجمة منظمة حسب الصفحات
const translations: Record<Language, Record<string, Record<string, string>>> = {
  ar: {
    login: {
      login: "تسجيل الدخول",
      email: "البريد الإلكتروني",
      password: "كلمة المرور",
      sign_in: "تسجيل الدخول",
      remember_me: "تذكرني",
      signing_in: "جاري تسجيل الدخول...",
      login_error: "خطأ في تسجيل الدخول",
      invalid_credentials: "بيانات الدخول غير صحيحة",
    },
    dashboard: {
      dashboard: "لوحة التحكم",
      welcome_message: "مرحباً بك في لوحة التحكم",
      dashboard_overview: "نظرة عامة",
      order_count: "عدد الطلبات",
      product_count: "عدد المنتجات",
      message_count: "عدد الرسائل",
      view_all: "عرض الكل",
      recent_orders: "الطلبات الحديثة",
      recent_messages: "الرسائل الحديثة",
    },
    navigation: {
      products: "المنتجات",
      orders: "الطلبات",
      messages: "الرسائل",
      profile: "الملف الشخصي",
      logout: "تسجيل الخروج",
    },
    products: {
      products: "المنتجات",
      all: "الكل",
      body_skin_care: "العناية بالبشرة والجسم",
      cosmetics: "مستحضرات التجميل",
      hair_care: "العناية بالشعر",
      hair_removal: "إزالة الشعر",
      personal_fragrance: "العطور الشخصية",
      add_product: "إضافة منتج",
      name: "الاسم",
      category: "الفئة",
      price: "السعر",
      stock: "المخزون",
      description: "الوصف",
      actions: "الإجراءات",
      edit: "تعديل",
      delete: "حذف",
      save: "حفظ",
      cancel: "إلغاء",
      search: "بحث",
      product_details: "تفاصيل المنتج",
      image: "الصورة",
      barcode: "الباركود",
      brand: "العلامة التجارية",
      in_stock: "متوفر",
      out_of_stock: "غير متوفر",
      showing_results: "عرض {0} من {1} منتج",
      bulk_add_json: "إضافة جماعية من JSON",
      add_new_product: "إضافة منتج جديد",
      edit_product: "تعديل المنتج",
      product_image: "صورة المنتج",
      product_image_url: "رابط صورة المنتج",
      case_size: "حجم العلبة",
      cases_per_layer: "علب لكل طبقة",
      cases_per_pallet: "علب لكل باليت",
      lead_time_days: "وقت التوصيل (أيام)",
      case_price: "سعر العلبة",
      unit_price: "سعر الوحدة",
      available: "متوفر",
      ingredients: "المكونات",
      usage: "طريقة الاستخدام",
      json_data: "بيانات JSON",
      bulk_add_products_json: "إضافة منتجات جماعية من JSON",
      prev: "السابق",
      next: "التالي",
      loading_products: "جاري تحميل المنتجات...",
      failed_fetch_products:
        "فشل في تحميل المنتجات. يرجى المحاولة مرة أخرى لاحقًا.",
      failed_add_product: "فشل في إضافة المنتج. يرجى المحاولة مرة أخرى.",
      failed_update_product: "فشل في تحديث المنتج. يرجى المحاولة مرة أخرى.",
      failed_delete_product: "فشل في حذف المنتج. يرجى المحاولة مرة أخرى.",
      failed_bulk_add: "فشل في إضافة المنتجات. يرجى التحقق من تنسيق JSON.",
      product_added_success: "تم إضافة المنتج بنجاح!",
      product_updated_success: "تم تحديث المنتج بنجاح!",
      product_deleted_success: "تم حذف المنتج بنجاح!",
      products_added_success: "تمت إضافة المنتجات بنجاح!",
      search_placeholder: "ابحث بالاسم، العلامة التجارية، أو الباركود",
      select_brand: "اختر علامة تجارية",
      select_category: "اختر فئة",
    },
    orders: {
      orders: "الطلبات",
      new_order: "طلب جديد",
      order_id: "رقم الطلب",
      customer: "العميل",
      date: "التاريخ",
      status: "الحالة",
      total: "المجموع",
      pending: "قيد الانتظار",
      completed: "مكتمل",
      shipped: "تم الشحن",
      cancelled: "ملغي",
      order_details: "تفاصيل الطلب",
      quantity: "الكمية",
      subtotal: "المجموع الجزئي",
      shipping_address: "عنقالشحن",
      payment_method: "طريقة الدفع",
      order_date: "تاريخ الطلب",
      customer_name: "اسم العميل",
      customer_email: "بريد العميل",
      customer_phone: "هاتف العميل",
    },
    messages: {
      messages: "الرسائل",
      new_message: "رسالة جديدة",
      message_id: "رقم الرسالة",
      subject: "الموضوع",
      received_at: "تاريخ الاستلام",
      read: "مقروء",
      unread: "غير مقروء",
      message_details: "تفاصيل الرسالة",
      content: "المحتوى",
      reply: "رد",
      mark_as_read: "وضع علامة مقروء",
      mark_as_unread: "وضع علامة غير مقروء",
      loading_messages: "جاري تحميل الرسائل...",
      no_messages: "لا توجد رسائل",
      close: "إغلاق",
      view: "عرض",
    },
    profile: {
      please_login_first: "يرجى تسجيل الدخول أولاً",
      failed_to_load_profile: "فشل تحميل بيانات الملف الشخصي",
      server_connection_error: "خطأ في الاتصال بالخادم",
      first_name_required: "الاسم الأول مطلوب",
      email_required: "البريد الإلكتروني مطلوب",
      invalid_email_format: "صيغة البريد الإلكتروني غير صحيحة",
      invalid_phone_format: "صيغة رقم الهاتف غير صحيحة",
      failed_to_update_profile: "فشل تحديث الملف الشخصي",
      current_password_required: "كلمة المرور الحالية مطلوبة",
      new_password_required: "كلمة المرور الجديدة مطلوبة",
      password_uppercase:
        "يجب أن تحتوي كلمة المرور على حرف كبير واحد على الأقل",
      password_lowercase:
        "يجب أن تحتوي كلمة المرور على حرف صغير واحد على الأقل",
      password_number: "يجب أن تحتوي كلمة المرور على رقم واحد على الأقل",
      password_special: "يجب أن تحتوي كلمة المرور على حرف خاص واحد على الأقل",
      password_length: "يجب أن تكون كلمة المرور مكونة من 8 أحرف على الأقل",
      passwords_not_match: "كلمات المرور غير متطابقة",
      failed_to_change_password: "فشل تغيير كلمة المرور",
      password_must_contain: "يجب أن تحتوي كلمة المرور على:",
      password_min_length: "8 أحرف على الأقل",
      not_specified: "غير محدد",
      not_provided: "غير مُقدم",
      profile: "الملف الشخصي",
      personal_information: "المعلومات الشخصية",
      first_name: "الاسم الأول",
      last_name: "الاسم الأخير",
      mobile_number: "رقم الهاتف المحمول",
      change_password: "تغيير كلمة المرور",
      current_password: "كلمة المرور الحالية",
      new_password: "كلمة المرور الجديدة",
      confirm_password: "تأكيد كلمة المرور",
      update: "تحديث",
      edit: "تعديل",
      save: "حفظ",
      cancel: "إلغاء",
      loading: "جاري التحميل...",
      session_expired: "انتهت الجلسة، يرجى تسجيل الدخول مرة أخرى",
      profile_updated_successfully: "تم تحديث الملف الشخصي بنجاح",
      current_password_incorrect: "كلمة المرور الحالية غير صحيحة",
      password_changed_successfully: "تم تغيير كلمة المرور بنجاح",
      invalid_data: "بيانات غير صالحة",
    },
    common: {
      search: "بحث",
      save: "حفظ",
      cancel: "إلغاء",
      edit: "تعديل",
      delete: "حذف",
      name: "الاسم",
      email: "البريد الإلكتروني",
      phone: "الهاتف",
      dashboard: "لوحة التحكم",
      products: "المنتجات",
      orders: "الطلبات",
      messages: "الرسائل",
      profile: "الملف الشخصي",
      logout: "تسجيل الخروج",
    },
  },
  en: {
    login: {
      login: "Login",
      email: "Email",
      password: "Password",
      sign_in: "Sign In",
      remember_me: "Remember me",
      signing_in: "Signing in...",
      login_error: "Login error",
      invalid_credentials: "Invalid credentials",
    },
    dashboard: {
      dashboard: "Dashboard",
      welcome_message: "Welcome to Dashboard",
      dashboard_overview: "Dashboard Overview",
      order_count: "Orders Count",
      product_count: "Products Count",
      message_count: "Messages Count",
      view_all: "View All",
      recent_orders: "Recent Orders",
      recent_messages: "Recent Messages",
    },
    navigation: {
      products: "Products",
      orders: "Orders",
      messages: "Messages",
      profile: "Profile",
      logout: "Logout",
    },
    products: {
      products: "Products",
      all: "All",
      body_skin_care: "Body & Skin Care",
      cosmetics: "Cosmetics",
      hair_care: "Hair Care",
      hair_removal: "Hair Removal",
      personal_fragrance: "Personal Fragrance",
      add_product: "Add Product",
      name: "Name",
      category: "Category",
      price: "Price",
      stock: "Stock",
      description: "Description",
      actions: "Actions",
      edit: "Edit",
      delete: "Delete",
      save: "Save",
      cancel: "Cancel",
      search: "Search",
      product_details: "Product Details",
      image: "Image",
      barcode: "Barcode",
      brand: "Brand",
      in_stock: "In Stock",
      out_of_stock: "Out of Stock",
      showing_results: "Showing {0} of {1} products",
      bulk_add_json: "Bulk Add from JSON",
      add_new_product: "Add New Product",
      edit_product: "Edit Product",
      product_image: "Product Image",
      product_image_url: "Product Image URL",
      case_size: "Case Size",
      cases_per_layer: "Cases Per Layer",
      cases_per_pallet: "Cases Per Pallet",
      lead_time_days: "Lead Time (Days)",
      case_price: "Case Price",
      unit_price: "Unit Price",
      available: "Available",
      ingredients: "Ingredients",
      usage: "Usage",
      json_data: "JSON Data",
      bulk_add_products_json: "Bulk Add Products from JSON",
      prev: "Prev",
      next: "Next",
      loading_products: "Loading products...",
      failed_fetch_products:
        "Failed to fetch products. Please try again later.",
      failed_add_product: "Failed to add product. Please try again.",
      failed_update_product: "Failed to update product. Please try again.",
      failed_delete_product: "Failed to delete product. Please try again.",
      failed_bulk_add: "Failed to add products. Please check your JSON format.",
      product_added_success: "Product added successfully!",
      product_updated_success: "Product updated successfully!",
      product_deleted_success: "Product deleted successfully!",
      products_added_success: "Products added successfully!",
      search_placeholder: "Search by name, brand, or barcode",
      select_brand: "Select a brand",
      select_category: "Select category",
    },
    orders: {
      orders: "Orders",
      new_order: "New Order",
      order_id: "Order ID",
      customer: "Customer",
      date: "Date",
      status: "Status",
      total: "Total",
      pending: "Pending",
      completed: "Completed",
      shipped: "Shipped",
      cancelled: "Cancelled",
      order_details: "Order Details",
      quantity: "Quantity",
      subtotal: "Subtotal",
      shipping_address: "Shipping Address",
      payment_method: "Payment Method",
      order_date: "Order Date",
      customer_name: "Customer Name",
      customer_email: "Customer Email",
      customer_phone: "Customer Phone",
    },
    messages: {
      messages: "Messages",
      new_message: "New Message",
      message_id: "Message ID",
      subject: "Subject",
      received_at: "Received At",
      read: "Read",
      unread: "Unread",
      message_details: "Message Details",
      content: "Content",
      reply: "Reply",
      mark_as_read: "Mark as Read",
      mark_as_unread: "Mark as Unread",
      loading_messages: "Loading messages...",
      no_messages: "No messages found",
      close: "Close",
      view: "View",
    },
    profile: {
      please_login_first: "Please log in first",
      failed_to_load_profile: "Failed to load profile data",
      server_connection_error: "Server connection error",
      first_name_required: "First name is required",
      email_required: "Email is required",
      invalid_email_format: "Invalid email format",
      invalid_phone_format: "Invalid phone number format",
      failed_to_update_profile: "Failed to update profile",
      current_password_required: "Current password is required",
      new_password_required: "New password is required",
      password_uppercase: "Password must include at least one uppercase letter",
      password_lowercase: "Password must include at least one lowercase letter",
      password_number: "Password must include at least one number",
      password_special: "Password must include at least one special character",
      password_length: "Password must be at least 8 characters long",
      passwords_not_match: "Passwords do not match",
      failed_to_change_password: "Failed to change password",
      password_must_contain: "Password must contain:",
      password_min_length: "At least 8 characters",
      not_specified: "Not specified",
      not_provided: "Not provided",
      personal_information: "Personal Information",
      first_name: "First Name",
      last_name: "Last Name",
      mobile_number: "Mobile Number",
      change_password: "Change Password",
      current_password: "Current Password",
      new_password: "New Password",
      confirm_password: "Confirm Password",
      update: "Update",
      profile: "Profile",
      loading: "Loading...",
      session_expired: "Session expired, please login again",
      profile_updated_successfully: "Profile updated successfully",
      current_password_incorrect: "Current password is incorrect",
      password_changed_successfully: "Password changed successfully",
      invalid_data: "Invalid data",
    },
    common: {
      search: "Search",
      save: "Save",
      cancel: "Cancel",
      edit: "Edit",
      delete: "Delete",
      name: "Name",
      email: "Email",
      phone: "Phone",
      dashboard: "Dashboard",
      products: "Products",
      orders: "Orders",
      messages: "Messages",
      profile: "Profile",
      logout: "Logout",
    },
  },
};

export const LanguageProvider: React.FC<LanguageProviderProps> = ({
  children,
}) => {
  const [language, setLanguage] = useState<Language>("ar");

  const toggleLanguage = () => {
    setLanguage((prev) => (prev === "ar" ? "en" : "ar"));
  };

  const t = (key: string, page: string = "common"): string => {
    return (
      translations[language][page]?.[key] ||
      translations[language]["common"]?.[key] ||
      key
    );
  };

  const isRTL = language === "ar";

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t, isRTL }}>
      <div className={isRTL ? "rtl" : "ltr"}>{children}</div>
    </LanguageContext.Provider>
  );
};
